"""
Generate a self-contained HTML report for exp40
(Global IMLE + exclusive Voronoi + recon + 2nd-nearest target, CIFAR-10).
Requires plots already generated by:
    CUDA_VISIBLE_DEVICES=0 uv run python projects/variations/scripts/gen_report_exp40.py

Usage:
    uv run python scripts/tmp/gen_html_report_exp40.py
"""

import sys, pickle, json, base64, io
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT))

from shared_lib.media import save_media

EXP      = "exp40"
PROJECT  = ROOT / "projects" / "variations"
PLOTS    = PROJECT / "plots"

with open(PROJECT / f"history_{EXP}.pkl", "rb") as f:
    history = pickle.load(f)

result = None
for line in (PROJECT / "results.jsonl").read_text().splitlines():
    r = json.loads(line)
    if r.get("experiment") == EXP:
        result = r
        break

n_params_val = result["n_params"]
time_s       = result["time_s"]
final_recon  = result["final_recon_mse"]
final_recall = result["final_recall_mse"]
latent_dim   = result["latent_dim"]
n_var        = result["n_var_samples"]
batch_size   = result["batch_size"]
alpha        = result["alpha"]
dc_c1, dc_c2, dc_c3, dc_stem = result["dc_c1"], result["dc_c2"], result["dc_c3"], result["dc_stem"]
enc_c1, enc_c2, enc_c3, enc_fc1 = result["enc_c1"], result["enc_c2"], result["enc_c3"], result["enc_fc1"]
n_cat, vocab_size = result["n_cat"], result["vocab_size"]
epochs_run   = len(history["loss"])

CIFAR_CLASSES = ["airplane", "automobile", "bird", "cat", "deer",
                 "dog", "frog", "horse", "ship", "truck"]

def to_uri(path):
    return "data:image/png;base64," + base64.b64encode(path.read_bytes()).decode()

curves_uri = to_uri(PLOTS / f"variations_{EXP}_curves.png")
recon_uri  = to_uri(PLOTS / f"variations_{EXP}_recon.png")
class_uris = {c: to_uri(PLOTS / f"variations_{EXP}_var_class{c}.png") for c in range(10)}
print("plots loaded")

def recall_curve_final(exp_name):
    for line in (PROJECT / "results.jsonl").read_text().splitlines():
        r = json.loads(line)
        if r.get("experiment") == exp_name:
            curve = r.get("eval_recall_mse_curve", [])
            return curve[-1][1] if curve else None
    return None

def recon_final(exp_name):
    for line in (PROJECT / "results.jsonl").read_text().splitlines():
        r = json.loads(line)
        if r.get("experiment") == exp_name:
            return r.get("final_recon_mse", r.get("final_mse", None))
    return None

exp35_recall = recall_curve_final("exp35")
exp39_recall = recall_curve_final("exp39")
exp38_recall = recall_curve_final("exp38")

best_recall  = min(v for _, v in result["eval_recall_mse_curve"])

def fmt(v):
    return f"{v:.5f}" if v is not None else "—"

OUTER_VALS_TEXT = "(0,0) (4,0) (0,4) (4,4)"

class_sections = ""
for c in range(10):
    class_sections += f"""
    <div class="class-block">
      <h3>Class {c} &mdash; {CIFAR_CLASSES[c].capitalize()}</h3>
      <p class="caption">
        <strong>Top row:</strong> source image + 10 global nearest neighbours (pixel L2 in training set). &nbsp;
        <strong>Middle row:</strong> zero-cat decode + closest of 256 variations to each global NN. &nbsp;
        <strong>Bottom:</strong> 16&times;16 mosaic — cat1 sweeps rows, cat2 sweeps cols,
        quadrants vary cat3&times;cat4 {OUTER_VALS_TEXT}.
      </p>
      <img src="{class_uris[c]}" alt="class {c} variations" class="plot full-width">
    </div>
"""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{EXP} — Global IMLE 2nd-nearest CIFAR-10</title>
  <style>
    :root{{--blue:#2563eb;--red:#dc2626;--green:#059669;--gray:#6b7280;--light:#f8fafc;--border:#e2e8f0;}}
    *{{box-sizing:border-box;margin:0;padding:0;}}
    body{{font-family:"Segoe UI",system-ui,sans-serif;font-size:15px;line-height:1.7;color:#1e293b;
         background:#fff;max-width:980px;margin:0 auto;padding:2.5rem 1.5rem 5rem;}}
    h1{{font-size:2rem;font-weight:700;color:#0f172a;margin-bottom:0.3rem;}}
    h2{{font-size:1.25rem;font-weight:700;color:#0f172a;border-bottom:2px solid var(--border);
        padding-bottom:0.4rem;margin:2.8rem 0 1rem;}}
    h3{{font-size:1rem;font-weight:600;color:#374151;margin:1.6rem 0 0.4rem;}}
    p{{margin-bottom:0.9rem;}}
    .subtitle{{color:var(--gray);font-size:0.93rem;margin:0.2rem 0 2rem;}}
    .summary-card{{background:var(--light);border:1px solid var(--border);border-radius:12px;
                   padding:1.4rem 1.6rem;margin-bottom:2.2rem;}}
    .metrics{{display:flex;gap:1rem;flex-wrap:wrap;margin:0.8rem 0 1rem;}}
    .metric{{background:#fff;border:1px solid var(--border);border-radius:8px;padding:0.55rem 1rem;
             min-width:130px;flex:1;}}
    .metric .label{{font-size:0.75rem;color:var(--gray);text-transform:uppercase;letter-spacing:0.05em;}}
    .metric .value{{font-size:1.3rem;font-weight:700;color:#0f172a;}}
    .callout{{border-left:4px solid var(--blue);background:#eff6ff;border-radius:0 8px 8px 0;
              padding:0.85rem 1.2rem;margin:1rem 0 1.2rem;}}
    .warn{{border-left:4px solid #f59e0b;background:#fffbeb;border-radius:0 8px 8px 0;
           padding:0.85rem 1.2rem;margin:1rem 0 1.2rem;}}
    table{{border-collapse:collapse;width:100%;margin:1rem 0 1.5rem;font-size:0.9rem;}}
    th{{background:var(--light);text-align:left;font-size:0.78rem;text-transform:uppercase;
        letter-spacing:0.04em;color:var(--gray);padding:0.5rem 0.9rem;border-bottom:2px solid var(--border);}}
    td{{padding:0.45rem 0.9rem;border-bottom:1px solid var(--border);}}
    tr:hover td{{background:var(--light);}}
    td:first-child{{font-weight:500;}}
    .plot{{display:block;max-width:100%;border-radius:8px;border:1px solid var(--border);margin:0.8rem 0 1.6rem;}}
    .full-width{{width:100%;}}
    .caption{{font-size:0.85rem;color:var(--gray);margin-bottom:0.4rem;}}
    .class-block{{margin-bottom:2.5rem;}}
    footer{{margin-top:4rem;padding-top:1.2rem;border-top:1px solid var(--border);
            font-size:0.8rem;color:var(--gray);text-align:center;}}
  </style>
</head>
<body>

<h1>Global IMLE — Exclusive Voronoi, 2nd-Nearest Target</h1>
<p class="subtitle">
  {EXP} &nbsp;·&nbsp; CIFAR-10 &nbsp;·&nbsp; CNN encoder + wide deconvnet &nbsp;·&nbsp;
  LATENT={latent_dim}, N_VAR={n_var}, early-stopped at epoch {epochs_run - 1} &nbsp;·&nbsp;
  {int(time_s // 60)} min on RTX 4090 &nbsp;·&nbsp; {n_params_val:,} parameters
</p>

<div class="summary-card">
  <strong style="font-size:1rem;">At a glance</strong>
  <div class="metrics">
    <div class="metric"><div class="label">Recall MSE (final)</div><div class="value">{final_recall:.4f}</div></div>
    <div class="metric"><div class="label">Best recall MSE</div><div class="value">{best_recall:.4f}</div></div>
    <div class="metric"><div class="label">Recon MSE (zero-cat)</div><div class="value">{final_recon:.4f}</div></div>
    <div class="metric"><div class="label">exp39 recall (1st-NN)</div><div class="value">{fmt(exp39_recall)}</div></div>
    <div class="metric"><div class="label">exp35 recall (local IMLE)</div><div class="value">{fmt(exp35_recall)}</div></div>
    <div class="metric"><div class="label">Training time</div><div class="value">{int(time_s//60)} min</div></div>
  </div>
  <p>
    exp40 = exp39 with one change: each variation targets its <strong>2nd-nearest</strong> training image
    within its exclusive Voronoi cell (instead of 1st-nearest). The hypothesis was that overshooting
    the nearest target might push variations further apart and improve local neighbourhood coverage.
    <code>top_k(k=2)</code> replaces <code>argmin</code> for the target selection — O(n) heap vs O(n log n) sort.
    Training is early-stopped when recall MSE shows no improvement (&gt;5×10⁻⁴) for 8 consecutive evals.
  </p>
  <div class="warn">
    <strong>Hypothesis rejected:</strong> recall MSE = {final_recall:.5f}, virtually identical to
    exp39 ({fmt(exp39_recall)}) and exp38 ({fmt(exp38_recall)}). The 2nd-nearest target did not
    improve coverage. Early stopping triggered at epoch {epochs_run - 1} (best recall {best_recall:.5f}
    at epoch 4), saving ~{int((200 - epochs_run) * 78 / 60)} minutes vs full 200-epoch run.
  </div>
</div>

<h2>Learning curves</h2>
<p class="caption">
  <strong>Left:</strong> total loss, L_imle (purple), L_recon (green) — all decrease, training is healthy.
  <strong>Centre:</strong> recon MSE and recall MSE — recall flat from epoch 4 onward.
  <strong>Right:</strong> per-rank recall MSE (blue = early → red = final) — no improvement over time.
  Vertical dashed line marks early-stop epoch.
</p>
<img src="{curves_uri}" alt="learning curves" class="plot full-width">

<h2>Zero-cat reconstructions (test set)</h2>
<p class="caption">
  32 test images. Odd rows = original; even rows = decoded with cats = all zeros.
  Recon MSE = {final_recon:.5f} — encoder learns good reconstructions despite only {epochs_run} epochs.
</p>
<img src="{recon_uri}" alt="reconstructions" class="plot full-width">

<h2>Variation grids — per class</h2>
<p>
  For one representative training image per CIFAR-10 class.
  The <strong>16&times;16 mosaic</strong> sweeps cat1 (rows) × cat2 (cols)
  with four quadrant combinations of cat3 and cat4 {OUTER_VALS_TEXT}.
  Top row: source + 10 <em>global</em> nearest neighbours.
  Middle row: zero-cat decode + closest of 256 variations to each global NN.
</p>

{class_sections}

<h2>Comparison — global IMLE ablation series</h2>
<table>
  <tr><th>Metric</th><th>exp35 (local IMLE)</th><th>exp38 (global, no recon)</th><th>exp39 (global + recon)</th><th>exp40 (global + 2nd-NN)</th></tr>
  <tr><td>Recall MSE</td><td>{fmt(exp35_recall)}</td><td>{fmt(exp38_recall)}</td><td>{fmt(exp39_recall)}</td><td><strong>{final_recall:.5f}</strong></td></tr>
  <tr><td>Recon MSE</td><td>{fmt(recon_final("exp35"))}</td><td>{fmt(recon_final("exp38"))}</td><td>{fmt(recon_final("exp39"))}</td><td>{final_recon:.5f}</td></tr>
  <tr><td>Target selection</td><td>Local K=16 NN</td><td>1st-NN in cell</td><td>1st-NN in cell</td><td><strong>2nd-NN in cell</strong></td></tr>
  <tr><td>Recon loss</td><td>Yes</td><td>No</td><td>Yes (α=1.0)</td><td>Yes (α=1.0)</td></tr>
  <tr><td>Epochs</td><td>200</td><td>200</td><td>200</td><td>{epochs_run} (early stop)</td></tr>
  <tr><td>Total time</td><td>~8.2h</td><td>~3.1h</td><td>~3.2h</td><td><strong>{int(time_s//60)} min</strong></td></tr>
</table>

<div class="callout">
  <strong>Conclusion:</strong> The recall gap vs exp35 is structural — global Voronoi cells cover
  ~781 training images each, spread across the full dataset, so variations cannot concentrate on the
  K=16 local neighbours of each input. Changing the target from 1st to 2nd nearest within the cell
  has no meaningful effect. Closing the gap requires biasing the matching toward local neighbourhoods,
  either via per-batch on-the-fly local NN or reverting to precomputed kNN.
</div>

<h2>Configuration</h2>
<table>
  <tr><th>Setting</th><th>Value</th></tr>
  <tr><td>Dataset</td><td>CIFAR-10 — 50,000 train / 10,000 test, 32×32 RGB</td></tr>
  <tr><td>Encoder</td><td>CNN: Conv({enc_c1}/{enc_c2}/{enc_c3}, stride-2) + FC({enc_fc1}→{latent_dim})</td></tr>
  <tr><td>Style variables</td><td>{n_cat} categorical, {vocab_size} values each → {vocab_size**n_cat:,} combinations</td></tr>
  <tr><td>Decoder channels</td><td>{dc_c1}/{dc_c2}/{dc_c3}, stem={dc_stem}</td></tr>
  <tr><td>Target selection</td><td>top_k(k=2) on negated masked distances → 2nd-nearest in Voronoi cell</td></tr>
  <tr><td>Loss function</td><td>L_imle(2nd-NN) + {alpha}·L_recon</td></tr>
  <tr><td>Early stopping</td><td>patience=8 evals, min_delta=5×10⁻⁴ on recall MSE</td></tr>
  <tr><td>Epochs / LR schedule</td><td>up to 200, cosine 3×10⁻⁴ → 1.5×10⁻⁵</td></tr>
  <tr><td>Total parameters</td><td>{n_params_val:,}</td></tr>
</table>

<footer>
  Conditioned variation model &nbsp;·&nbsp; {EXP} &nbsp;·&nbsp; CIFAR-10 &nbsp;·&nbsp;
  Global IMLE + exclusive Voronoi + 2nd-nearest &nbsp;·&nbsp; 2026-04-23
</footer>
</body>
</html>"""

r2_url = save_media(
    f"variations_{EXP}_report.html",
    io.BytesIO(html.encode("utf-8")),
    "text/html"
)
print(f"R2 URL → {r2_url}")
