// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/condition_bars.json"),
  mapping: aes(x: "condition", y: "nmse", fill: "trained on"),
  layers: (
    geom-col(width: 0.72, stroke: none),
    geom-hline(yintercept: 1.0, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
  ),
  scales: scales(y: scale-continuous(), x: scale-discrete(limits: ("A", "B", "C", "D")), fill: scale-discrete(limits: ("recall only", "completion only", "mixed"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73")))),
  labels: labels(x: "condition", y: "final normalised MSE", fill: "trained on"),
  theme: theme-minimal(),
  width: 13cm,
  height: 7cm,
  alt: "Final normalised MSE for each evaluation condition, grouped by what the model was trained on.",
)
