// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/context_size.json"),
  mapping: aes(x: "M", y: "nmse", colour: "what", fill: "what"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
    geom-hline(yintercept: 1.0, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
    geom-text(data: (x: (225.76,), y: (1.0,), label: ("predict the mean image",)), mapping: aes(x: "x", y: "y", label: "label"), size: 7pt, colour: luma(110), nudge-y: 0.018939423832306918, inherit-aes: false),
  ),
  scales: scales(x: scale-continuous(), y: scale-continuous(), colour: scale-discrete(limits: ("recall-trained model", "best soft look-up from context"), palette: (rgb("#0072b2"), rgb("#d55e00"))), fill: scale-discrete(limits: ("recall-trained model", "best soft look-up from context"), palette: (rgb("#0072b2"), rgb("#d55e00")))),
  labels: labels(x: "context images per episode (M)", y: "normalised MSE, condition D", colour: "", fill: ""),
  theme: theme-minimal(),
  width: 13cm,
  height: 7.5cm,
  alt: "Normalised MSE on the novel-context, absent-target condition against the number of context images, for the recall-trained model and for the best soft look-up from the context.",
)
