// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/divergence.json"),
  mapping: aes(x: "step", y: "nmse", colour: "condition", fill: "condition"),
  layers: (
    geom-line(size: 1.1pt),
    geom-hline(yintercept: 1.0, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
    geom-text(data: (x: (10620.0,), y: (1.0,), label: ("predict the mean image",)), mapping: aes(x: "x", y: "y", label: "label"), size: 7pt, colour: luma(110), nudge-y: 0.023448261911373506, inherit-aes: false),
  ),
  scales: scales(x: scale-continuous(), y: scale-continuous(), colour: scale-discrete(limits: ("A  seen ctx, target present", "B  novel ctx, target present", "C  seen ctx, target absent", "D  novel ctx, target absent"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7"))), fill: scale-discrete(limits: ("A  seen ctx, target present", "B  novel ctx, target present", "C  seen ctx, target absent", "D  novel ctx, target absent"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7")))),
  labels: labels(x: "training step", y: "normalised MSE", colour: "condition", fill: "condition"),
  theme: theme-minimal(),
  width: 14cm,
  height: 8cm,
  alt: "Normalised MSE against training step for four evaluation conditions. The two conditions whose target is present in the context fall towards zero; the two whose target is absent rise towards the mean-image reference line at 1.0.",
)
