// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/length_transfer.json"),
  mapping: aes(x: "M", y: "gain", colour: "model", fill: "model"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
    geom-hline(yintercept: 0.0, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
    geom-text(data: (x: (225.76,), y: (0.0,), label: ("the context is not being read",)), mapping: aes(x: "x", y: "y", label: "label"), size: 7pt, colour: luma(110), nudge-y: 0.023760454474400124, inherit-aes: false),
  ),
  scales: scales(x: scale-log10(), y: scale-continuous(), colour: scale-discrete(limits: ("trained on recall, 16 in context", "trained on recall, 256 in context", "trained to complete"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"))), fill: scale-discrete(limits: ("trained on recall, 16 in context", "trained on recall, 256 in context", "trained to complete"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73")))),
  labels: labels(x: "context images at test time (log scale)", y: "gain", colour: "", fill: ""),
  theme: theme-minimal(),
  width: 13cm,
  height: 7.5cm,
  alt: "Gain against test-time context size for three trained models. The model trained at 16 stays well above zero until 256; the models trained at 256 and on completion sit on zero throughout.",
)
