// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/state_size.json"),
  mapping: aes(x: "state", y: "nmse", colour: "condition", fill: "condition"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
    geom-hline(yintercept: 1.0, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
    geom-text(data: (x: (14663.68,), y: (1.0,), label: ("predict the mean image",)), mapping: aes(x: "x", y: "y", label: "label"), size: 7pt, colour: luma(110), nudge-y: 0.02343165830363269, inherit-aes: false),
  ),
  scales: scales(x: scale-continuous(), y: scale-continuous(), colour: scale-discrete(limits: ("A  retrieval (target present)", "D  completion (target absent)"), palette: (rgb("#0072b2"), rgb("#d55e00"))), fill: scale-discrete(limits: ("A  retrieval (target present)", "D  completion (target absent)"), palette: (rgb("#0072b2"), rgb("#d55e00")))),
  labels: labels(x: "numbers in the recurrent state", y: "normalised MSE", colour: "", fill: ""),
  theme: theme-minimal(),
  width: 13cm,
  height: 7.5cm,
  alt: "Normalised MSE on the retrieval and completion conditions against the size of the recurrent state, with the context size held at 16.",
)
