"""
exp25 — gram_inner_embed: replace factored f3 embedding with a tiny inner Gram RNN.

Instead of the f3 Kronecker embedding (row_emb[r] ⊗ col_emb[c] ⊗ val_emb[bin]),
the embedding for each pixel is generated by a small Gram-based sub-network:

  1. Look up three d_i-dim tokens for (row, col, val_bin)
       pos_emb[row],  pos_emb[col],   val_emb[bin]      (shared pos table 0-27)
  2. Build inner Gram (sum of outer products):
       M_in = pos_e_r⊗pos_e_r + pos_e_c⊗pos_e_c + val_e⊗val_e  ∈ R^{d_i×d_i}
  3. Single-query bilinear readout:
       h_in = M_in @ q_in                                ∈ R^{d_i}
  4. LN + linear projection:
       emb_t = LN(h_in) @ W_proj.T + b_proj              ∈ R^{d_o}

This emb_t replaces the f3 embedding in the outer Gram bilinear model.

Key properties vs f3:
  • Inner Gram captures pairwise interactions (row×col, row×val, col×val) — richer
    than the pure Kronecker product which only models the 3-way multiplicative term.
  • Decouples inner dimension d_i (embedding table size) from output d_o (outer
    Gram dimension). f3 forces d = d_r * d_c * d_v; gram_inner_embed can produce
    any d_o from a small d_i.
  • Very few emb params: pos_emb(28×d_i) + val_emb(32×d_i) + q_in(d_i) +
    W_proj(d_o×d_i) + b_proj(d_o) + LN(2×d_i) = (62+d_o)*d_i + d_o
    e.g. d_i=4, d_o=16: (62+16)*4+16 = 328 emb params vs f3(4,4,4): 352 emb params.

  ALL inner embedding params are classified as "emb" (excluded from the x-axis
  non-emb plot). The outer model non-emb formula is identical to existing f3 bilinear:
    non_emb = K*d_o*(3+mlp) + depth*2*d_o + 11*mlp + 10

Existing MNIST Pareto front checkpoints (non-emb params → test acc):
  ~270  → 88.36% (joint K=1 mlp=16)
  ~416  → 93.06% (joint d=32 bilinear)
  ~522  → 95.25% (joint d=16 K=1 mlp=16)
  ~954  → 96.02% (joint d=16 K=1 mlp=32)
  ~1818 → 96.93% (joint d=16 K=1 mlp=64)
  ~2602 → 97.20% (f3 bilinear K=4 mlp=32)
  ~5130 → 97.72% (f3 bilinear K=1 mlp=64)
  ~7530 → 97.94% (f3 bilinear K=1 mlp=96)
  ~35082→ 98.54% (f3 bilinear K=4 mlp=128)

Usage:
    uv run python projects/rnn/experiments25.py
"""

import json, time, sys, subprocess
from pathlib import Path
from functools import partial

import jax
import jax.numpy as jnp
import optax
import logging

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from shared_lib.random_utils import infinite_safe_keys_from_key
from shared_lib.datasets import load_supervised_image

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

N_VAL_BINS = 32
BATCH_SIZE = 128
LR         = 1e-3
LR_MUON    = 0.02
SEED       = 42

JSONL = Path(__file__).parent / "results_mnist.jsonl"
PLOT  = Path(__file__).parent / "plot_pareto_gram_embed.py"

ROWS = jnp.arange(784) // 28
COLS = jnp.arange(784) % 28


# ── utilities ─────────────────────────────────────────────────────────────────

def layer_norm(x, gamma, beta, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var  = jnp.var(x,  axis=-1, keepdims=True)
    return gamma * (x - mean) / jnp.sqrt(var + eps) + beta

def n_nonemb(p, emb_keys):
    return sum(v.size for k, v in p.items() if k not in emb_keys)

def n_total(p):
    return sum(v.size for v in jax.tree_util.tree_leaves(p))

def append_result(row):
    with open(JSONL, "a") as f:
        f.write(json.dumps(row) + "\n")

def random_noise_batch(imgs, rng, scale=30.0):
    noise = jax.random.uniform(rng, imgs.shape, minval=-scale, maxval=scale)
    return jnp.clip(imgs + noise, 0.0, 255.0)


# ── Muon optimizer ────────────────────────────────────────────────────────────

def _newton_schulz(G, steps=5):
    a, b, c = 3.4445, -4.7750, 2.0315
    norm = jnp.linalg.norm(G)
    X = G / (norm + 1e-7)
    for _ in range(steps):
        A = X @ X.T
        X = a*X + b*(A@X) + c*(A@(A@X))
    return X * norm

def ns_nesterov_direction(momentum=0.95):
    def init(p): return {"mu": jax.tree_util.tree_map(jnp.zeros_like, p)}
    def update(g, s, p=None):
        mu   = s["mu"]
        mu2  = jax.tree_util.tree_map(lambda m, gi: momentum*m + gi, mu, g)
        nest = jax.tree_util.tree_map(lambda m, gi: momentum*m + gi, mu2, g)
        out  = jax.tree_util.tree_map(
            lambda gi: _newton_schulz(gi) if gi.ndim == 2 else gi, nest)
        return out, {"mu": mu2}
    return optax.GradientTransformation(init, update)

def make_muon_tx(params, emb_keys, adam_sched, muon_sched):
    mat_keys = frozenset(k for k, v in params.items()
                         if v.ndim == 2 and k not in emb_keys)
    labels = {k: "muon" if k in mat_keys else "adam" for k in params}
    return optax.chain(
        optax.clip_by_global_norm(1.0),
        optax.multi_transform({
            "muon": optax.chain(ns_nesterov_direction(),
                                optax.scale_by_learning_rate(muon_sched)),
            "adam": optax.adam(adam_sched),
        }, labels),
    )


# ── gram_inner_embed + outer bilinear ─────────────────────────────────────────

# All inner embedding network params — excluded from non-emb x-axis
GRAM_EMB_KEYS = frozenset({
    "pos_emb",      # (28, d_i)  shared for row and col
    "val_emb",      # (32, d_i)
    "q_in",         # (d_i,)     inner readout query
    "ge_ln_gamma",  # (d_i,)     LN before projection
    "ge_ln_beta",   # (d_i,)
    "W_proj",       # (d_o, d_i) linear projection to outer dim
    "b_proj",       # (d_o,)
})


def make_gram_inner_embed(d_i, d_o, mlp_dim, n_queries=1, depth=1):
    """gram_inner_embed + outer Gram bilinear.

    Inner embedding network (all in GRAM_EMB_KEYS, excluded from non-emb):
      pos_emb(28×d_i) + val_emb(32×d_i) + q_in(d_i) +
      LN(2×d_i) + W_proj(d_o×d_i) + b_proj(d_o)
      = (62+d_o)*d_i + d_o  emb params

    Outer non-emb (same formula as f3 bilinear with d=d_o):
      K*d_o*(3+mlp) + depth*2*d_o + 11*mlp + 10
    """
    feat_dim = n_queries * d_o
    kg       = infinite_safe_keys_from_key(jax.random.PRNGKey(SEED))

    p = {
        # ── inner embedding network ───────────────────────────────────────────
        "pos_emb":      jax.random.normal(next(kg).get(), (28, d_i))     * 0.02,
        "val_emb":      jax.random.normal(next(kg).get(), (N_VAL_BINS, d_i)) * 0.02,
        "q_in":         jax.random.normal(next(kg).get(), (d_i,))        * 0.02,
        "ge_ln_gamma":  jnp.ones(d_i),
        "ge_ln_beta":   jnp.zeros(d_i),
        "W_proj":       jax.random.normal(next(kg).get(), (d_o, d_i))    / d_i**0.5,
        "b_proj":       jnp.zeros(d_o),
        # ── outer model ───────────────────────────────────────────────────────
        "H_answer":     jax.random.normal(next(kg).get(), (n_queries, d_o)) * 0.02,
        "ln_out_gamma": jnp.ones(feat_dim),
        "ln_out_beta":  jnp.zeros(feat_dim),
        "W1": jax.random.normal(next(kg).get(), (mlp_dim, feat_dim)) / feat_dim**0.5,
        "b1": jnp.zeros(mlp_dim),
        "W2": jax.random.normal(next(kg).get(), (10, mlp_dim))       * 0.01,
        "b2": jnp.zeros(10),
    }
    for i in range(depth):
        p[f"ln_hop{i}_gamma"] = jnp.ones(d_o)
        p[f"ln_hop{i}_beta"]  = jnp.zeros(d_o)

    def _inner_emb(params, x):
        """Compute per-pixel embedding via inner Gram. Returns (B, 784, d_o)."""
        B    = x.shape[0]
        bins = jnp.floor(x / 255.0 * (N_VAL_BINS - 1)).astype(jnp.int32)

        # Inner token embeddings
        re = params["pos_emb"][ROWS]   # (784, d_i) — row
        ce = params["pos_emb"][COLS]   # (784, d_i) — col (shared pos table)
        ve = params["val_emb"][bins]   # (B, 784, d_i)

        # Inner Gram: position part is batch-independent (precomputable)
        M_pos = (jnp.einsum("ti,tj->tij", re, re) +
                 jnp.einsum("ti,tj->tij", ce, ce))  # (784, d_i, d_i)
        M_val = jnp.einsum("bti,btj->btij", ve, ve)  # (B, 784, d_i, d_i)
        M_in  = M_pos[None] + M_val                   # (B, 784, d_i, d_i)

        # Readout, LN, project
        h_in = jnp.einsum("btij,j->bti", M_in, params["q_in"])  # (B, 784, d_i)
        h_in = layer_norm(h_in, params["ge_ln_gamma"], params["ge_ln_beta"])
        return h_in @ params["W_proj"].T + params["b_proj"]       # (B, 784, d_o)

    def fwd(params, x):
        emb = _inner_emb(params, x)          # (B, 784, d_o)
        M   = jnp.einsum("bti,btj->bij", emb, emb)  # (B, d_o, d_o)
        outs = []
        for q in range(n_queries):
            h = jnp.broadcast_to(params["H_answer"][q], (emb.shape[0], d_o))
            for i in range(depth):
                h = jnp.einsum("bij,bj->bi", M, h)
                h = layer_norm(h, params[f"ln_hop{i}_gamma"],
                               params[f"ln_hop{i}_beta"])
            outs.append(h)
        features = jnp.concatenate(outs, axis=-1)
        features = layer_norm(features, params["ln_out_gamma"], params["ln_out_beta"])
        h = jax.nn.gelu(features @ params["W1"].T + params["b1"])
        return h @ params["W2"].T + params["b2"]

    return fwd, p, GRAM_EMB_KEYS


# ── training loop ─────────────────────────────────────────────────────────────

def train(name, fwd, params, emb_keys, X_tr, y_tr, X_te, y_te, max_epochs=30):
    num_batches = len(X_tr) // BATCH_SIZE
    total_steps = max_epochs * num_batches
    adam_sched  = optax.cosine_decay_schedule(LR,      total_steps)
    muon_sched  = optax.cosine_decay_schedule(LR_MUON, total_steps)
    tx        = make_muon_tx(params, emb_keys, adam_sched, muon_sched)
    opt_state = tx.init(params)
    key_gen   = infinite_safe_keys_from_key(jax.random.PRNGKey(SEED + 1))
    loss_fn   = lambda p, bx, by: jnp.mean(
        optax.softmax_cross_entropy_with_integer_labels(fwd(p, bx), by))

    def acc_fn(p, x, y):
        preds = jnp.concatenate([
            jnp.argmax(fwd(p, x[i:i+BATCH_SIZE]), 1)
            for i in range(0, len(x), BATCH_SIZE)])
        return float(jnp.mean(preds == y))

    @partial(jax.jit, static_argnums=(0,))
    def step(opt_, p, s, bx, by):
        loss, g = jax.value_and_grad(loss_fn)(p, bx, by)
        u, s2   = opt_.update(g, s, p)
        return optax.apply_updates(p, u), s2, loss

    t0 = time.perf_counter()
    train_acc = test_acc = 0.0
    for epoch in range(max_epochs):
        key  = next(key_gen).get()
        perm = jax.random.permutation(key, len(X_tr))
        Xs, ys = X_tr[perm], y_tr[perm]
        aug_rng = key
        for b in range(num_batches):
            s, e   = b * BATCH_SIZE, (b+1) * BATCH_SIZE
            bx, by = Xs[s:e], ys[s:e]
            aug_rng, sub = jax.random.split(aug_rng)
            bx = random_noise_batch(bx, sub)
            params, opt_state, _ = step(tx, params, opt_state, bx, by)
        train_acc = acc_fn(params, X_tr, y_tr)
        test_acc  = acc_fn(params, X_te, y_te)
        logging.info(f"[{name}] epoch {epoch:2d}  train={train_acc:.4f}  "
                     f"test={test_acc:.4f}  {time.perf_counter()-t0:.1f}s")
    return train_acc, test_acc, time.perf_counter() - t0


if __name__ == "__main__":
    logging.info("Loading MNIST...")
    data    = load_supervised_image("mnist")
    X_train = data.X.reshape(data.n_samples,           -1).astype(jnp.float32)
    X_test  = data.X_test.reshape(data.n_test_samples, -1).astype(jnp.float32)
    y_train, y_test = data.y, data.y_test

    # non_emb = K*d_o*(3+mlp) + depth*2*d_o + 11*mlp + 10
    # emb     = (62+d_o)*d_i + d_o   (tiny, ~300-700 params across all configs)
    experiments = [
        # ── ultra-small (<500 non-emb) ────────────────────────────────────────
        # 186 non-emb: beats joint K=1 mlp=16 at 270 non-emb (83.61%)?
        ("gram_embed(4→8) K=1 mlp=8 +noise30",
         *make_gram_inner_embed(4, 8,  8,  n_queries=1)),
        # 274 non-emb: same as joint K=4 mlp=16 (93.53%)
        ("gram_embed(4→16) K=1 mlp=8 +noise30",
         *make_gram_inner_embed(4, 16, 8,  n_queries=1)),
        # 490 non-emb: same as joint d=16 K=1 mlp=16 (95.25%)
        ("gram_embed(4→16) K=1 mlp=16 +noise30",
         *make_gram_inner_embed(4, 16, 16, n_queries=1)),

        # ── small (500–2000 non-emb) ──────────────────────────────────────────
        # 794 non-emb: same as reshape_1h K=1 mlp=16 (95.63%)
        ("gram_embed(4→16) K=2 mlp=16 +noise30",
         *make_gram_inner_embed(4, 16, 16, n_queries=2)),
        # 922 non-emb: same as joint d=16 K=1 mlp=32 (96.02%)
        ("gram_embed(4→16) K=1 mlp=32 +noise30",
         *make_gram_inner_embed(4, 16, 32, n_queries=1)),
        # 1482 non-emb: same as joint d=16 K=2 mlp=32 (96.23%)
        ("gram_embed(4→16) K=2 mlp=32 +noise30",
         *make_gram_inner_embed(4, 16, 32, n_queries=2)),
        # 1786 non-emb: same as joint d=16 K=1 mlp=64 (96.93%)
        ("gram_embed(4→16) K=1 mlp=64 +noise30",
         *make_gram_inner_embed(4, 16, 64, n_queries=1)),

        # ── medium (2000–10K non-emb) ─────────────────────────────────────────
        # 2602 non-emb: same as f3 bilinear K=4 mlp=32 (97.20%)
        ("gram_embed(4→16) K=4 mlp=32 +noise30",
         *make_gram_inner_embed(4, 16, 32, n_queries=4)),
        # 2858 non-emb
        ("gram_embed(4→16) K=2 mlp=64 +noise30",
         *make_gram_inner_embed(4, 16, 64, n_queries=2)),
        # 5002 non-emb: same as f3 bilinear K=4 mlp=64 (≈97.7%)
        ("gram_embed(4→16) K=4 mlp=64 +noise30",
         *make_gram_inner_embed(4, 16, 64, n_queries=4)),
        # 9322 non-emb: in range of f3 K=1 mlp=96 (97.94%)
        ("gram_embed(4→64) K=4 mlp=32 +noise30",
         *make_gram_inner_embed(4, 64, 32, n_queries=4)),
        # 9802 non-emb
        ("gram_embed(4→16) K=4 mlp=128 +noise30",
         *make_gram_inner_embed(4, 16, 128, n_queries=4)),

        # ── high end (~35K non-emb) ───────────────────────────────────────────
        # 34954 non-emb: same as f3 K=4 mlp=128 (98.54%)
        ("gram_embed(4→64) K=4 mlp=128 +noise30",
         *make_gram_inner_embed(4, 64, 128, n_queries=4)),
    ]

    results = []
    for label, fwd, params, emb_keys in experiments:
        nonemb = n_nonemb(params, emb_keys)
        ntotal = n_total(params)
        logging.info(f"\n{'='*60}\n{label}\n"
                     f"  non-emb={nonemb:,}  total={ntotal:,}\n{'='*60}")
        tr_acc, te_acc, elapsed = train(
            label, fwd, params, emb_keys,
            X_train, y_train, X_test, y_test)
        row = {
            "name": label, "experiment": "exp25",
            "family": "gram_embed",
            "n_nonemb_params": nonemb,
            "n_total_params":  ntotal,
            "train_acc": round(tr_acc, 6), "test_acc": round(te_acc, 6),
            "epochs": 30, "time_s": round(elapsed, 1), "notes": "",
        }
        append_result(row)
        results.append((label, nonemb, ntotal, tr_acc, te_acc))
        logging.info(f"  → train={tr_acc:.4f}  test={te_acc:.4f}")

    results.sort(key=lambda r: r[1])
    print(f"\n{'='*110}")
    print(f"{'Variant':<52} {'NonEmb':>8} {'Total':>8} {'Train':>8} {'Test':>8}")
    print(f"{'-'*110}")
    for label, nonemb, ntotal, tr, te in results:
        print(f"{label:<52} {nonemb:>8,} {ntotal:>8,} {tr:>8.4f} {te:>8.4f}")
    print(f"{'='*110}")

    subprocess.run([sys.executable, str(PLOT)], check=False)
