"""
Modular Typst reports: author sections as `.typ`, compile with typst-py, publish to R2.

The unit of authorship is a *section file*. A report is a directory:

    report/
      main.typ              entry — page setup and the section order
      template.typ          shared styles and helpers (#fig, #callout, #kv, …)
      sections/*.typ        hand-written prose, one file per section
      figures/*.typ         generated by shared_lib.typst_plot (do not edit)
      assets/*.json         generated figure data (do not edit)
      .build.json           file hashes and URLs from the last publish

Because every part is a separate file, updating a report is partial by nature:
rewrite one section (or regenerate one figure), recompile, publish again.
`changed_since_publish()` reports exactly which files moved, and
`preview_section()` renders a single section on its own for fast iteration
without touching R2.

Typical use from a project's `scripts/publish_report.py`:

    from shared_lib.typst_plot import write_figures
    from shared_lib.typst_report import changed_since_publish, publish_report

    write_figures(REPORT, build_figures())
    print(changed_since_publish(REPORT))
    urls = publish_report("omniglot-ar_report", REPORT)

Paths inside the report are root-relative (`/sections/…`, `/figures/…`), with
the report directory itself as the Typst root — so files can be moved between
sections without rewriting their imports. Typst evaluates an `#include`d file
in its own scope, so each section starts with `#import "/template.typ": *` to
get `#fig`, `#callout`, and `#kv`.

Publishing stores **only the PDF**. The HTML page that gets shared is ~3 KB and
renders that PDF client-side with pdf.js from a CDN, so a report does not also
cost a few hundred KB of SVG showing the same content. Pass `with_svg=True` if
somewhere needs a script-free rendering.

`stable=True` publishes to an undated key that is overwritten in place, so a
link shared once keeps resolving to the current version. That is what a living
document needs; one-shot reports should keep the default date-prefixed key.

`save_figure()` renders a single `typst_plot.Figure` on its own — no report
tree, data inlined — and uploads it as an image. That is what lets a markdown
report and the paper draw from one set of figure definitions.
"""

from __future__ import annotations

import hashlib
import json
import re
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from .html import save_html
from .media import save_media

BUILD_FILE = ".build.json"
ENTRY = "main.typ"

# Where stable (republished-in-place) documents live, and how long the edge may
# hold one. Five minutes is long enough to absorb a burst of readers and short
# enough that a republish is visible while you are still at the keyboard.
STABLE_DIR = "paper"
STABLE_CACHE_CONTROL = "public, max-age=300, must-revalidate"

# Files that make up the report's content, for change tracking. Everything else
# in the directory (build state, rendered output) is derived and ignored.
_TRACKED_SUFFIXES = (".typ", ".json", ".csv", ".svg", ".png", ".jpg")

# Rendered previews land in the report root as out.pdf / out.svg / out.png and
# share suffixes with real assets, so they are excluded by name — otherwise
# every preview would show up as a content change.
_DERIVED_STEMS = ("out",)


@dataclass(frozen=True)
class ReportURLs:
    """Where a published report ended up."""

    page: str          # HTML viewer — the link to share
    pdf: str           # the compiled PDF
    svg: str | None = None   # only when publish_report(with_svg=True)

    def __str__(self) -> str:
        return self.page


# ──────────────────────────────── compiling ─────────────────────────────────


def _compiler(report_dir: Path, entry: str):
    try:
        import typst
    except ImportError as e:  # pragma: no cover - dependency is declared
        raise ImportError(
            "typst is required for Typst reports — it is in pyproject.toml; "
            "install with `uv pip install typst`"
        ) from e
    entry_path = report_dir / entry
    if not entry_path.exists():
        raise FileNotFoundError(f"report entry not found: {entry_path}")
    return typst.Compiler(str(entry_path), root=str(report_dir))


def compile_report(
    report_dir: str | Path,
    *,
    entry: str = ENTRY,
    fmt: str = "pdf",
    web: bool = False,
    inputs: Mapping[str, str] | None = None,
) -> bytes:
    """Compile a report tree and return the rendered bytes.

    `web=True` sets the `web` system input, which `main.typ` uses to switch to a
    single continuously-flowing page — the right shape for the HTML viewer,
    where paper-sized pagination only adds seams.
    """
    report_dir = Path(report_dir)
    sys_inputs = {"web": "1" if web else "0", **(dict(inputs) if inputs else {})}
    out = _compiler(report_dir, entry).compile(format=fmt, sys_inputs=sys_inputs)
    if isinstance(out, list):        # multi-page SVG/PNG comes back as a list
        if len(out) != 1:
            raise ValueError(
                f"expected a single {fmt} page, got {len(out)}; "
                "compile with web=True so the page height is automatic"
            )
        out = out[0]
    return out if isinstance(out, bytes) else bytes(out, "utf-8")


def preview(
    report_dir: str | Path,
    out_path: str | Path,
    *,
    entry: str = ENTRY,
    fmt: str = "pdf",
) -> Path:
    """Compile to a local file without uploading. Returns the path written."""
    data = compile_report(report_dir, entry=entry, fmt=fmt)
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    return out


# A section previewed alone still refers to labels defined in its siblings, and
# Typst fails the whole compile on an unresolved one. These find what to stub.
#
# Both reference spellings have to be handled. `@key` is the common one, but
# `#link(<key>)[7.4]` is what you write to point at a specific subsection with
# your own text, and real papers here use it far more than `@`.
_REF_RE = re.compile(r"(?<![\w@])@([A-Za-z][\w:.-]*[\w]|[A-Za-z])")
_LINK_REF_RE = re.compile(r"#(?:link|ref)\(\s*<([A-Za-z][\w:.-]*)>")
_LABEL_RE = re.compile(r"<([A-Za-z][\w:.-]*)>")
_BIB_KEY_RE = re.compile(r"^\s*@\w+\s*\{\s*([^,\s]+)\s*,", re.M)


def label_uses(text: str) -> tuple[set[str], set[str]]:
    """Split label mentions into (defined here, referenced from here).

    `<key>` is the same token in both roles, so a mention inside `#link(...)`
    or `#ref(...)` is a reference and every other one is a definition.
    """
    linked = set(_LINK_REF_RE.findall(text))
    defined = set(_LABEL_RE.findall(text)) - linked
    referenced = linked | set(_REF_RE.findall(text))
    return defined, referenced


def _cross_section_stubs(report_dir: Path, section_text: str) -> str:
    """Hidden placeholders for labels this section references but does not own.

    Without them, previewing a section that says "see @sec:analysis" fails with
    `label <sec:analysis> does not exist` — which is every real paper, since
    cross-references are what sections are for.

    Stubs are zero-height hidden headings. They carry their own `set heading`
    numbering because Typst refuses to reference an unnumbered heading and the
    short-report template does not number at all; scoping it to the block keeps
    the previewed section's own headings looking as they should. A reference to
    a figure or table in another section resolves to a section-style reference
    this way rather than a figure-style one — wrong supplement, right preview.
    """
    defined, referenced = label_uses(section_text)
    referenced -= defined
    if not referenced:
        return ""
    bib = report_dir / "refs.bib"
    if bib.exists():
        referenced -= set(_BIB_KEY_RE.findall(bib.read_text(encoding="utf-8")))
    if not referenced:
        return ""
    stubs = "\n".join(f"  hide[= Elsewhere <{key}>]" for key in sorted(referenced))
    return (
        "// Stubs for labels defined in sections not part of this preview.\n"
        "#block(height: 0pt, {\n"
        '  set heading(numbering: "1.1")\n'
        f"{stubs}\n"
        "})\n"
    )


def show_rule_fn(report_dir: str | Path, *, entry: str = ENTRY, default: str = "report") -> str:
    """The show-rule function `main.typ` applies — `report`, `paper`, whatever.

    Detected rather than configured: passing the wrong name is a silent
    mismatch between a tree and the script that previews it, and the entry file
    already states the answer on its `#show:` line.
    """
    path = Path(report_dir) / entry
    if not path.exists():
        return default
    m = re.search(r"^\s*#show:\s*([A-Za-z][\w-]*)", path.read_text(encoding="utf-8"), re.M)
    return m.group(1) if m else default


def preview_section(
    report_dir: str | Path,
    section: str,
    out_path: str | Path,
    *,
    fmt: str = "svg",
    template_fn: str | None = None,
) -> Path:
    """Render one section on its own, through the tree's template.

    `section` is the stem of a file in `sections/` (e.g. `"03-results"`). This
    is the fast iteration loop: no other section is compiled, no figure outside
    it is read, nothing is uploaded.

    `template_fn` is the show-rule function the template exports; it is read off
    `main.typ` when not given. Two things are injected so a section compiles
    outside its document: a `refs.bib` bibliography when one exists, since Typst
    resolves `@key` against the bibliography rather than the citation, and
    hidden stubs for labels owned by sibling sections.
    """
    report_dir = Path(report_dir)
    target = report_dir / "sections" / f"{section}.typ"
    if not target.exists():
        available = sorted(p.stem for p in (report_dir / "sections").glob("*.typ"))
        raise FileNotFoundError(
            f"no section {section!r} in {report_dir / 'sections'} "
            f"(have: {', '.join(available) or 'none'})"
        )

    fn = template_fn or show_rule_fn(report_dir)
    stubs = _cross_section_stubs(report_dir, target.read_text(encoding="utf-8"))
    # Untitled so a section with no citations does not sprout an empty heading.
    bib = ""
    if (report_dir / "refs.bib").exists():
        bib = '#bibliography("/refs.bib", title: none, style: "ieee")\n'

    entry = report_dir / ".preview.typ"
    entry.write_text(
        "// Temporary single-section preview — regenerated on every call.\n"
        '#import "/template.typ": *\n'
        f"#show: {fn}.with(title: {_typ_str(f'preview — {section}')}, web: true)\n"
        f'#include "/sections/{section}.typ"\n'
        f"{stubs}{bib}",
        encoding="utf-8",
    )
    try:
        data = compile_report(report_dir, entry=".preview.typ", fmt=fmt, web=True)
    finally:
        entry.unlink(missing_ok=True)

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    return out


# ───────────────────────────── standalone figures ───────────────────────────

# A figure rendered on its own gets a page shrink-wrapped around it. The small
# margin keeps axis labels from touching the edge of the image box.
_FIGURE_ENTRY = (
    "// Generated by shared_lib.typst_report.render_figure — not written to disk.\n"
    "#import {package}: *\n"
    "#set page(width: auto, height: auto, margin: {margin}, fill: {fill})\n"
    "#{call}\n"
)


def render_figure(
    figure,
    *,
    fmt: str = "svg",
    margin: str = "4pt",
    fill: str = "white",
) -> bytes:
    """Compile one `typst_plot.Figure` on its own and return the image bytes.

    The data is inlined into the generated source, so this needs no report tree
    and no `assets/` file — `Figure.typst()` takes the data expression as an
    argument precisely so it can come from somewhere other than `json(...)`.

    SVG carries text as outlines, so the result renders identically inside an
    `<img>` with no font available. It also grows with the number of points,
    while PNG does not: past a few hundred points per series, prefer `png`.
    """
    from .typst_plot import GRIBOUILLE, typ  # local: keeps typst_plot import-light

    src = _FIGURE_ENTRY.format(
        package=typ(GRIBOUILLE),
        margin=margin,
        fill=fill,
        call=figure.typst(typ(figure.data)),
    )
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        entry = root / "figure.typ"
        entry.write_text(src, encoding="utf-8")
        return compile_report(root, entry="figure.typ", fmt=fmt)


def save_figure(
    figure,
    *,
    name: str | None = None,
    fmt: str = "svg",
    margin: str = "4pt",
    fill: str = "white",
    stable: bool = False,
) -> str:
    """Render a `Figure` standalone and upload it. Returns the URL.

    The markdown-report counterpart to `write_figures()`, which aims the same
    `Figure` at a Typst tree instead. One figure definition can therefore feed
    an intermediate report and the paper without being written twice.

        from shared_lib.typst_plot import line_chart
        from shared_lib.typst_report import save_figure

        url = save_figure(line_chart("acc", data, x="step", y="acc"))
        md = f"![Accuracy over training]({url})"

    `stable` behaves as it does for `publish_report`: an undated key that is
    overwritten, carrying the short cache lifetime that makes overwriting
    visible. Default off — a figure in a one-shot report should keep the
    immutable URL it was published under.
    """
    stem = name or getattr(figure, "name", None) or "figure"
    data = render_figure(figure, fmt=fmt, margin=margin, fill=fill)
    content_type = "image/svg+xml" if fmt == "svg" else f"image/{fmt}"
    return save_media(
        f"{stem}.{fmt}", data, content_type,
        key_dir=STABLE_DIR if stable else None,
        cache_control=STABLE_CACHE_CONTROL if stable else None,
    )


# ───────────────────────────── change tracking ──────────────────────────────


def _typ_str(s: str) -> str:
    """A Typst string literal. Non-ASCII stays literal UTF-8 — Typst's escape
    syntax is `\\u{2014}`, not JSON's `\\u2014`, so `json.dumps` defaults would
    emit an em dash as six visible characters.
    """
    return json.dumps(s, ensure_ascii=False)


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def _fill(text: str, **values: str) -> str:
    """Substitute `{name}` placeholders, leaving every other brace alone.

    Not `str.format`: the templates being filled are Typst source, where `{`
    opens a code block. `str.format` would raise on the first one somebody adds
    to a scaffold file, which is a trap for whoever edits the template next.
    """
    return re.sub(
        r"\{(" + "|".join(map(re.escape, values)) + r")\}",
        lambda m: values[m.group(1)],
        text,
    )


def content_hashes(report_dir: str | Path) -> dict[str, str]:
    """Hash every tracked content file, keyed by path relative to the report."""
    root = Path(report_dir)
    return {
        str(p.relative_to(root)): _sha(p)
        for p in sorted(root.rglob("*"))
        if p.is_file()
        and p.suffix in _TRACKED_SUFFIXES
        and p.name != BUILD_FILE
        and not p.name.startswith(".")
        and not (p.parent == root and p.stem in _DERIVED_STEMS)
    }


def read_build_state(report_dir: str | Path) -> dict:
    """The state recorded by the last successful publish (empty if never)."""
    path = Path(report_dir) / BUILD_FILE
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


@dataclass(frozen=True)
class Changes:
    """What moved in the report tree since the last publish."""

    added: tuple[str, ...] = ()
    modified: tuple[str, ...] = ()
    removed: tuple[str, ...] = ()

    @property
    def any(self) -> bool:
        return bool(self.added or self.modified or self.removed)

    def __str__(self) -> str:
        if not self.any:
            return "no changes since last publish"
        parts = [
            f"{tag} {', '.join(files)}"
            for tag, files in (("+", self.added), ("~", self.modified), ("-", self.removed))
            if files
        ]
        return "; ".join(parts)


def changed_since_publish(report_dir: str | Path) -> Changes:
    """Compare the tree against `.build.json` — the partial-update summary."""
    now = content_hashes(report_dir)
    before = read_build_state(report_dir).get("files", {})
    return Changes(
        added=tuple(sorted(k for k in now if k not in before)),
        modified=tuple(sorted(k for k, v in now.items() if k in before and before[k] != v)),
        removed=tuple(sorted(k for k in before if k not in now)),
    )


# ──────────────────────────────── publishing ────────────────────────────────

# The viewer renders the PDF client-side with pdf.js from a CDN, so the PDF is
# the only artefact stored — no per-page SVG or PNG. That is both far less R2
# space and one source of truth: what you download is exactly what you read.
_PDFJS_VERSION = "4.6.82"
_PDFJS_CDN = f"https://cdn.jsdelivr.net/npm/pdfjs-dist@{_PDFJS_VERSION}/build"

_VIEWER_CSS = """
:root { color-scheme: light dark; --bg:#f4f4f5; --fg:#18181b; --edge:rgb(0 0 0 / .12); }
@media (prefers-color-scheme: dark) { :root { --bg:#18181b; --fg:#e4e4e7; --edge:rgb(0 0 0 / .5); } }
* { box-sizing: border-box; }
body { margin:0; padding:1.25rem 1rem 4rem; background:var(--bg); color:var(--fg);
       font:15px/1.55 ui-sans-serif,-apple-system,"Segoe UI",Helvetica,sans-serif; }
header { max-width:920px; margin:0 auto 1rem; display:flex; flex-wrap:wrap; gap:.75rem;
         align-items:baseline; justify-content:space-between; }
h1 { font-size:1.05rem; font-weight:600; margin:0; }
.meta { font:12px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace; opacity:.65; }
a.dl { font:12px/1 ui-monospace,SFMono-Regular,Menlo,monospace; text-decoration:none;
       border:1px solid currentColor; border-radius:5px; padding:.4rem .6rem;
       color:inherit; opacity:.8; }
a.dl:hover { opacity:1; }
#pages { max-width:920px; margin:0 auto; display:flex; flex-direction:column; gap:1rem; }
#pages canvas { display:block; width:100%; height:auto; background:#fff;
                border-radius:6px; box-shadow:0 1px 4px var(--edge); }
#status { max-width:920px; margin:0 auto; font:13px/1.5 ui-monospace,monospace; opacity:.7; }
#status a { color:inherit; }
"""

_VIEWER_JS = """
import * as pdfjsLib from '__CDN__/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc = '__CDN__/pdf.worker.min.mjs';

const url = '__PDF__';
const status = document.getElementById('status');
const pages = document.getElementById('pages');
// 2x for crisp text on HiDPI; CSS scales each canvas to the container width.
const SCALE = 2;

try {
  const pdf = await pdfjsLib.getDocument(url).promise;

  // Every page gets a correctly-sized placeholder canvas up front, so the
  // scrollbar is right immediately and nothing reflows as pages fill in.
  const first = (await pdf.getPage(1)).getViewport({ scale: SCALE });

  // Rasterise only what is near the viewport. A long paper rendered eagerly
  // spends seconds of CPU on pages nobody has scrolled to yet.
  const io = new IntersectionObserver(async (entries) => {
    for (const entry of entries) {
      if (!entry.isIntersecting) continue;
      const canvas = entry.target;
      io.unobserve(canvas);
      const page = await pdf.getPage(Number(canvas.dataset.page));
      const viewport = page.getViewport({ scale: SCALE });
      canvas.width = viewport.width;
      canvas.height = viewport.height;
      await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise;
    }
  }, { rootMargin: '1200px 0px' });

  for (let n = 1; n <= pdf.numPages; n++) {
    const canvas = document.createElement('canvas');
    canvas.dataset.page = String(n);
    canvas.width = first.width;
    canvas.height = first.height;
    pages.appendChild(canvas);
    io.observe(canvas);
  }
  status.textContent = pdf.numPages + ' pages';
} catch (e) {
  status.innerHTML = 'Could not render inline (' + e.message +
    '). <a href="' + url + '">Open the PDF directly</a>.';
}
"""


def _viewer_html(title: str, pdf_url: str, built_at: str) -> str:
    """A self-contained page that renders `pdf_url` with pdf.js from a CDN.

    Only the PDF is stored; this page is ~3 KB. If the CDN or the render fails
    the status line degrades to a direct link, so the report is never
    unreachable because a script did not load.
    """
    js = _VIEWER_JS.replace("__CDN__", _PDFJS_CDN).replace("__PDF__", pdf_url)
    return (
        "<!DOCTYPE html>\n<html lang='en'>\n<head>\n"
        "  <meta charset='utf-8'>\n"
        "  <meta name='viewport' content='width=device-width, initial-scale=1'>\n"
        f"  <title>{title}</title>\n"
        f"  <style>{_VIEWER_CSS}</style>\n"
        "</head>\n<body>\n"
        "  <header>\n"
        f"    <h1>{title}</h1>\n"
        f"    <span class='meta'>built {built_at}</span>\n"
        f"    <a class='dl' href='{pdf_url}'>PDF ↓</a>\n"
        "  </header>\n"
        "  <div id='pages'></div>\n"
        "  <p id='status'>rendering…</p>\n"
        f"  <script type='module'>{js}</script>\n"
        "</body>\n</html>\n"
    )


def publish_report(
    name: str,
    report_dir: str | Path,
    *,
    title: str | None = None,
    entry: str = ENTRY,
    with_svg: bool = False,
    record: bool = True,
    stable: bool = False,
) -> ReportURLs:
    """Compile a report and upload the PDF plus a small pdf.js viewer page.

    The PDF is the only artefact stored. The viewer renders it client-side from
    a CDN, so a report costs ~1 PDF instead of a PDF *and* a multi-hundred-KB
    SVG of the same content. `with_svg=True` restores the old SVG upload for
    somewhere that cannot run scripts.

    `stable=True` writes to an undated key, overwritten on every publish, with
    a short cache lifetime. Use it for a document that is republished as work
    proceeds and whose link is shared before it is finished — a date-prefixed
    key would leave every previously shared link pointing at a stale version,
    which is worse than a dead one because it still renders. Leave it off for
    one-shot reports, where an immutable URL per publish is the better
    property.

    Returns the URLs; the viewer page is the one to share. On success the build
    state is recorded in `.build.json`, so the next `changed_since_publish()` is
    measured against exactly what was pushed.
    """
    report_dir = Path(report_dir)
    stem = name[:-4] if name.lower().endswith(".pdf") else name
    built_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    key_dir = STABLE_DIR if stable else None
    cache = STABLE_CACHE_CONTROL if stable else None

    pdf = compile_report(report_dir, entry=entry, fmt="pdf", web=False)
    pdf_url = save_media(f"{stem}.pdf", pdf, "application/pdf",
                         key_dir=key_dir, cache_control=cache)

    svg_url = None
    if with_svg:
        svg = compile_report(report_dir, entry=entry, fmt="svg", web=True)
        svg_url = save_media(f"{stem}.svg", svg, "image/svg+xml",
                             key_dir=key_dir, cache_control=cache)

    page_url = save_html(stem, _viewer_html(title or stem, pdf_url, built_at),
                         key_dir=key_dir, cache_control=cache)

    urls = ReportURLs(page=page_url, pdf=pdf_url, svg=svg_url)
    if record:
        recorded = {"page": page_url, "pdf": pdf_url}
        if svg_url:
            recorded["svg"] = svg_url
        (report_dir / BUILD_FILE).write_text(
            json.dumps(
                {
                    "name": stem,
                    "published_at": built_at,
                    "stable": stable,
                    "urls": recorded,
                    "files": content_hashes(report_dir),
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
    return urls


# ──────────────────────────────── scaffolding ───────────────────────────────

_TEMPLATE_TYP = '''// Shared styling and helpers for this report. Hand-written — edit freely.

#let accent = rgb("#0072b2")
#let muted = luma(105)

// Print pages are A4; `web: true` keeps the A4 width but lets the page grow to
// one continuous strip, which is what the HTML viewer embeds.
#let report(title: "", subtitle: none, date: none, web: false, body) = {
  set page(
    width: 21cm,
    height: if web { auto } else { 29.7cm },
    margin: (x: 2.2cm, y: 2.2cm),
    numbering: if web { none } else { "1" },
  )
  // No font family: Typst's bundled default (New Computer Modern) renders
  // identically on macOS and on the GPU box. Naming Helvetica here silently
  // fell back to a different face on Linux, so the same report looked
  // different depending on where it was compiled.
  set text(size: 10pt, lang: "en")
  set par(justify: true, leading: 0.68em)
  show heading: set block(above: 1.5em, below: 0.8em)
  show heading.where(level: 1): set text(size: 15pt, weight: 700)
  show heading.where(level: 2): set text(size: 12pt, weight: 700)
  show heading.where(level: 3): set text(size: 10.5pt, weight: 700, fill: muted)
  show link: set text(fill: accent)
  set table(stroke: (x, y) => (top: if y <= 1 { 0.5pt } else { 0pt },
                               bottom: 0.5pt))
  show table.cell.where(y: 0): strong

  block(width: 100%, {
    text(size: 20pt, weight: 700, title)
    if subtitle != none { linebreak(); text(size: 11pt, fill: muted, subtitle) }
    if date != none { linebreak(); text(size: 9pt, fill: muted, date) }
  })
  line(length: 100%, stroke: 0.5pt + muted)
  v(0.6em)
  body
}

// Place a generated figure: #fig(include "/figures/x.typ", caption: [...])
#let fig(body, caption: none) = figure(body, caption: caption, kind: image)

// A boxed aside for a caveat, a decision, or a result worth not missing.
#let callout(title: none, body) = block(
  width: 100%, inset: 10pt, radius: 4pt,
  fill: accent.lighten(92%), stroke: (left: 2pt + accent),
  {
    if title != none { text(weight: 700, size: 9.5pt, title); linebreak() }
    set text(size: 9.5pt)
    body
  },
)

// A compact key/value block for run settings.
#let kv(..pairs) = block(
  width: 100%,
  table(
    columns: (auto, 1fr),
    stroke: none,
    inset: (x: 0pt, y: 3pt),
    column-gutter: 12pt,
    ..pairs.pos().map(p => (text(fill: muted, size: 9pt, p.at(0)),
                            text(size: 9pt, raw(str(p.at(1)))))).flatten(),
  ),
)
'''

_MAIN_TYP = '''// Report entry point. The section list below IS the report's structure —
// add, remove, or reorder #include lines; each section is an independent file.

#import "/template.typ": *

#show: report.with(
  title: {title},
  subtitle: {subtitle},
  date: {date},
  web: sys.inputs.at("web", default: "0") == "1",
)

{includes}
'''

# Typst evaluates an `#include`d file in its own scope, so every section has to
# pull in the template itself — inheriting it from main.typ is not a thing.
_SECTION_TYP = '''#import "/template.typ": *

= {heading}

TODO: write this section.
'''


# The paper scaffold ships as real .typ files rather than Python strings, so it
# stays editable and previewable as Typst. `main.typ.in` and `gitignore.in` are
# format templates; everything else is copied verbatim.
_PAPER_TEMPLATE_DIR = Path(__file__).parent / "templates" / "paper"

PAPER_SECTIONS = (
    "01-introduction",
    "02-background",
    "03-task",
    "04-methodology",
    "05-experiments",
    "06-results",
    "07-analysis",
    "08-limitations",
    "09-conclusion",
)


def scaffold_paper(
    paper_dir: str | Path,
    *,
    title: str,
    subtitle: str | None = None,
    date: str | None = None,
    sections: Sequence[str] = PAPER_SECTIONS,
    overwrite: bool = False,
) -> list[Path]:
    """Create a paper tree — the long-form, self-contained kind.

    Unlike `scaffold_report`, this is meant to be created at the *start* of a
    project and republished as work proceeds: the sections carry their
    obligations as comments and their unwritten passages as `#todo`, so the
    tree doubles as the checklist. `check_paper()` reports what is still open;
    building with `status: "final"` turns every remaining `#todo` into a
    compile error.

    Existing files are left alone unless `overwrite=True`, so this is safe to
    re-run to add a section to a paper already being written.
    """
    root = Path(paper_dir)
    (root / "sections").mkdir(parents=True, exist_ok=True)
    (root / "figures").mkdir(parents=True, exist_ok=True)
    (root / "assets").mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    def write(path: Path, text: str) -> None:
        if path.exists() and not overwrite:
            return
        path.write_text(text, encoding="utf-8")
        written.append(path)

    def source(name: str) -> str:
        return (_PAPER_TEMPLATE_DIR / name).read_text(encoding="utf-8")

    write(root / "template.typ", source("template.typ"))
    write(root / "refs.bib", source("refs.bib"))
    write(root / ".gitignore", source("gitignore.in"))
    write(
        root / ENTRY,
        _fill(
            source("main.typ.in"),
            title=_typ_str(title),
            subtitle=_typ_str(subtitle) if subtitle else "none",
            date=_typ_str(date) if date else "none",
            paper_dir=root.as_posix(),
            includes="\n".join(f'#include "/sections/{s}.typ"' for s in sections),
        ),
    )

    for s in sections:
        stub = _PAPER_TEMPLATE_DIR / "sections" / f"{s}.typ"
        if stub.exists():
            write(root / "sections" / f"{s}.typ", stub.read_text(encoding="utf-8"))
        else:
            # A section the caller invented; give it the generic body.
            heading = s.split("-", 1)[-1].replace("-", " ").capitalize()
            write(
                root / "sections" / f"{s}.typ",
                f'#import "/template.typ": *\n\n= {heading}\n\n#todo[write this section]\n',
            )
    return written


def scaffold_report(
    report_dir: str | Path,
    *,
    title: str,
    subtitle: str | None = None,
    date: str | None = None,
    sections: Sequence[str] = ("01-summary", "02-method", "03-results"),
    overwrite: bool = False,
) -> list[Path]:
    """Create a report tree — template, entry, and one file per section.

    Existing files are left alone unless `overwrite=True`, so this is safe to
    re-run to add sections to a report already being written.
    """
    root = Path(report_dir)
    (root / "sections").mkdir(parents=True, exist_ok=True)
    (root / "figures").mkdir(parents=True, exist_ok=True)
    (root / "assets").mkdir(parents=True, exist_ok=True)

    def write(path: Path, text: str) -> None:
        if path.exists() and not overwrite:
            return
        path.write_text(text, encoding="utf-8")
        written.append(path)

    written: list[Path] = []
    write(root / "template.typ", _TEMPLATE_TYP)
    write(
        root / ENTRY,
        _MAIN_TYP.format(
            title=_typ_str(title),
            subtitle=_typ_str(subtitle) if subtitle else "none",
            date=_typ_str(date) if date else "none",
            includes="\n".join(f'#include "/sections/{s}.typ"' for s in sections),
        ),
    )
    for s in sections:
        heading = s.split("-", 1)[-1].replace("-", " ").capitalize()
        write(root / "sections" / f"{s}.typ", _SECTION_TYP.format(heading=heading))
    return written
