// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/ablation.json"),
  mapping: aes(x: "task", y: "accuracy", fill: "trained"),
  layers: (geom-col(width: 0.72, stroke: none, position: "dodge"),),
  scales: scales(y: scale-continuous(limits: (0.0, 1.0)), x: scale-discrete(limits: ("mod. add", "needle", "decimal", "parens")), fill: scale-discrete(limits: ("all three (E_token, E_pos, U)", "E_token & U", "E_token & E_pos", "U only"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7")))),
  labels: labels(x: "task", y: "sequence accuracy", fill: "optimised"),
  theme: theme-minimal(),
  width: 16cm,
  height: 7.5cm,
  alt: "Grouped bars showing sequence accuracy at width 1024 when different subsets of the embedding matrices are optimised.",
)
