// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/circuit_imitation.json"),
  mapping: aes(x: "target_width", y: "kl", colour: "student", fill: "student"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
  ),
  scales: scales(x: scale-log10(), y: scale-continuous(), colour: scale-discrete(limits: ("random student", "fully trained student"), palette: (rgb("#0072b2"), rgb("#d55e00"))), fill: scale-discrete(limits: ("random student", "fully trained student"), palette: (rgb("#0072b2"), rgb("#d55e00")))),
  labels: labels(x: "width of the target circuit", y: "held-out KL divergence", colour: "", fill: ""),
  theme: theme-minimal(),
  width: 13cm,
  height: 7cm,
  alt: "KL divergence from a random target transformer against the target's hidden width, on a log scale, for random and fully trained students.",
)
