// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/lm_scaling.json"),
  mapping: aes(x: "width", y: "loss", colour: "model", fill: "model"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
  ),
  scales: scales(x: scale-log10(), y: scale-continuous(), colour: scale-discrete(limits: ("random, 2 layers", "random, 4 layers", "fully trained, 2 layers", "fully trained, 4 layers"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7"))), fill: scale-discrete(limits: ("random, 2 layers", "random, 4 layers", "fully trained, 2 layers", "fully trained, 4 layers"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7")))),
  labels: labels(x: "hidden width", y: "validation cross-entropy (nats/token)", colour: "", fill: ""),
  theme: theme-minimal(),
  width: 13cm,
  height: 7.5cm,
  alt: "Validation cross-entropy on TinyStories against hidden width on a log scale, for random and fully trained transformers at two depths.",
)
