// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/main_table.json"),
  mapping: aes(x: "task", y: "accuracy", fill: "condition"),
  layers: (geom-col(width: 0.72, stroke: none, position: "dodge"),),
  scales: scales(y: scale-continuous(limits: (0.0, 1.0)), x: scale-discrete(limits: ("mod. add", "needle", "decimal", "parens")), fill: scale-discrete(limits: ("random 1024", "random 16", "trained 1024", "trained 16", "LSTM 1024", "chance"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7"), rgb("#e69f00"), rgb("#56b4e9")))),
  labels: labels(x: "task", y: "sequence accuracy", fill: "model"),
  theme: theme-minimal(),
  width: 16cm,
  height: 7.5cm,
  alt: "Grouped bars of sequence accuracy on four algorithmic tasks for random and fully trained transformers at widths 1024 and 16, a fully trained LSTM, and the chance level for each task.",
)
