// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/memorization_bits.json"),
  mapping: aes(x: "model", y: "bits"),
  layers: (geom-col(width: 0.72, stroke: none, fill: rgb("#0072b2")),),
  scales: scales(y: scale-continuous()),
  labels: labels(x: "model", y: "bits per trainable parameter"),
  theme: theme-minimal(),
  width: 10cm,
  height: 7cm,
  alt: "Bits of arbitrary association stored per trainable parameter, for fully trained and random transformers on the memorization task.",
)
