// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/subspace_L1.json"),
  mapping: aes(x: "task", y: "variance", fill: "basis"),
  layers: (geom-col(width: 0.72, stroke: none, position: "dodge"),),
  scales: scales(y: scale-continuous(limits: (0.0, 1.0)), x: scale-discrete(limits: ("mod. add", "needle", "decimal", "parens", "memorize")), fill: scale-discrete(limits: ("random: top 10 components", "random: top 10 neurons", "trained: top 10 components", "trained: top 10 neurons"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"), rgb("#cc79a7")))),
  labels: labels(title: "activations after layer 1", x: "task", y: "fraction of variance explained", fill: ""),
  theme: theme-minimal(),
  width: 17cm,
  height: 7.5cm,
  alt: "Grouped bars comparing the fraction of activation variance explained by the top ten principal components against the top ten individual neurons, per task and training regime.",
)
