// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/width_needle.json"),
  mapping: aes(x: "width", y: "accuracy", colour: "training", fill: "training"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
    geom-hline(yintercept: 0.0079, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
    geom-text(data: (x: (903.04,), y: (0.0079,), label: ("chance",)), mapping: aes(x: "x", y: "y", label: "label"), size: 7pt, colour: luma(110), nudge-y: 0.028, inherit-aes: false),
  ),
  scales: scales(x: scale-log10(), y: scale-continuous(limits: (0.0, 1.0)), colour: scale-discrete(limits: ("random (embeddings only)", "fully trained"), palette: (rgb("#0072b2"), rgb("#d55e00"))), fill: scale-discrete(limits: ("random (embeddings only)", "fully trained"), palette: (rgb("#0072b2"), rgb("#d55e00")))),
  labels: labels(title: "needle-in-a-haystack", x: "hidden width", y: "sequence accuracy", colour: "", fill: ""),
  theme: theme-minimal(),
  width: 13cm,
  height: 7cm,
  alt: "Sequence accuracy on needle-in-a-haystack against hidden width on a log scale, for embedding-only and fully trained models, with a dashed chance line.",
)
