// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/crossover.json"),
  mapping: aes(x: "s", y: "solve", colour: "architecture", fill: "architecture"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
  ),
  scales: scales(x: scale-continuous(), y: scale-continuous(limits: (-0.04, 1.04)), colour: scale-discrete(limits: ("transformer", "static mixer", "KDA"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73"))), fill: scale-discrete(limits: ("transformer", "static mixer", "KDA"), palette: (rgb("#0072b2"), rgb("#d55e00"), rgb("#009e73")))),
  labels: labels(x: "row sparsity s (positions the pattern must select)", y: "fraction of 16 seeds solving", colour: "architecture", fill: "architecture"),
  theme: theme-minimal(),
  width: 12cm,
  height: 7cm,
  alt: "Solve rate against sparsity for transformer, static mixer and KDA.",
)
