// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/emergence_spread.json"),
  mapping: aes(x: "rank", y: "step", colour: "run", fill: "run"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
  ),
  scales: scales(x: scale-continuous(), y: scale-continuous(), colour: scale-discrete(limits: ("exp1", "exp4"), palette: (rgb("#0072b2"), rgb("#d55e00"))), fill: scale-discrete(limits: ("exp1", "exp4"), palette: (rgb("#0072b2"), rgb("#d55e00")))),
  labels: labels(x: "seed, ordered by emergence time", y: "step at which it emerged", colour: "run", fill: "run"),
  theme: theme-minimal(),
  width: 12cm,
  height: 7cm,
  alt: "Sorted time-to-emergence for two independent 16-seed samples.",
)
