// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/induction.json"),
  mapping: aes(x: "architecture", y: "recall"),
  layers: (
    geom-col(width: 0.72, stroke: none, fill: rgb("#0072b2")),
    geom-hline(yintercept: 0.03125, linetype: "dashed", colour: luma(130), stroke: 0.6pt),
  ),
  scales: scales(y: scale-continuous(limits: (0.0, 1.05)), x: scale-discrete(limits: ("transformer", "static mixer", "KDA"))),
  labels: labels(x: "architecture", y: "median recall accuracy"),
  theme: theme-minimal(),
  width: 11cm,
  height: 7cm,
  alt: "Median recall accuracy on induction for each architecture.",
)
