// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/kofm_k.json"),
  mapping: aes(x: "k", y: "solve", colour: "variant", fill: "variant"),
  layers: (
    geom-line(size: 1.1pt),
    geom-point(size: 2.6pt),
  ),
  scales: scales(x: scale-continuous(), y: scale-continuous(limits: (-0.04, 1.04)), colour: scale-discrete(limits: ("ambiguous match", "unique match"), palette: (rgb("#0072b2"), rgb("#d55e00"))), fill: scale-discrete(limits: ("ambiguous match", "unique match"), palette: (rgb("#0072b2"), rgb("#d55e00")))),
  labels: labels(x: "k — relevant attributes the match depends on (of m = 8)", y: "fraction of 16 seeds solving", colour: "task variant", fill: "task variant"),
  theme: theme-minimal(),
  width: 12cm,
  height: 7cm,
  alt: "Solve rate rising with k for both variants of the k-of-m task.",
)
