// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/kofm_candidates.json"),
  mapping: aes(x: "cell", y: "solve"),
  layers: (geom-col(width: 0.72, stroke: none, fill: rgb("#0072b2")),),
  scales: scales(y: scale-continuous(limits: (0.0, 1.05)), x: scale-discrete(limits: ("k=1, C=8", "k=2, C=28", "k=6, C=28", "k=3, C=56", "k=4, C=70"))),
  labels: labels(x: "ordered by candidate count C(m, k)", y: "fraction of seeds solving"),
  theme: theme-minimal(),
  width: 11cm,
  height: 7cm,
  alt: "Solve rate ordered by candidate count, showing no relationship.",
)
