// Generated by shared_lib.typst_plot — do not edit by hand.
// Regenerate with the project's scripts/gen_report.py.
#import "@preview/gribouille:0.6.0": *

#plot(
  data: json("/assets/pool_gain.json"),
  mapping: aes(x: "pool", y: "gain"),
  layers: (geom-col(width: 0.72, stroke: none, fill: rgb("#0072b2")),),
  scales: scales(y: scale-continuous(), x: scale-discrete(limits: ("1", "16", "256", "4096", "fresh"))),
  labels: labels(x: "rule pool size N (fresh = a new rule every sequence)", y: "in-context gain (per-state loss, first − last)"),
  theme: theme-minimal(),
  width: 11cm,
  height: 7cm,
  alt: "In-context gain against rule pool size.",
)
